---
title: "DAT4500"
output: html_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(openintro)
library(readxl)
library(plotly)
library(readr)
library(tibble)
library(albersusa)

my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())}

us_states <- usa_sf()
us_county <- counties_sf("laea")

Labels <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/lehd_types_s3.csv")
County <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_county.csv")
Tract <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/job_loss_by_tract.csv")
CBSA <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_cbsa.csv")
```

## Data

```{r Camalcase}
Lab <- c("TotalJobLossIndex", "Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin")

LabChange <- County[,-1:-3]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- County[,-4:-28]
NoChangeLast <- County[, -1:-24]
County <- cbind(NoChangeFirst, LabChange, NoChangeLast)

LabChange <- CBSA[,-1:-2]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- CBSA[,-3:-27]
NoChangeLast <- CBSA[, -1:-23]
CBSA <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin", "TotalJobLossIndex")

LabChange <- Tract[,-1:-7]
LabChange <- LabChange[,-22:-23]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- Tract[,-8:-30]
NoChangeLast <- Tract[, -1:-28]
Tract <- cbind(NoChangeFirst, LabChange, NoChangeLast)
```

## Recompile for All States

```{r}
CountryByState <- County %>%
  select(state_name, TotalJobLossIndex, total_li_workers_employed, Agriculture, Mining, Utilities, Construction, Manufacturing, Wholesale_Trade, Retail_Trade, Transportation_Warehousing, Information, Finance_Insurance, RealEstate, STEM, CorpManagement, WasteManagement, Education, Health_SocialAssistance, Arts, Accommodations_FoodService, OtherServices, PublicAdmin)%>%
  group_by(state_name) %>%
    summarize(
      ProportionOfJobLossIndexToLowIncomeJobs = sum(TotalJobLossIndex) / sum(total_li_workers_employed),
      TotalJobLossIndex = sum(TotalJobLossIndex),
      total_li_workers_employed = sum(total_li_workers_employed),
      Agriculture = sum(Agriculture),
      Mining = sum(Mining),
      Utilities = sum(Utilities),
      Construction = sum(Construction),
      Manufacturing = sum(Manufacturing),
      Wholesale_Trade = sum(Wholesale_Trade),
      Retail_Trade = sum(Retail_Trade),
      Transportation_Warehousing = sum(Transportation_Warehousing),
      Information = sum(Information),
      Finance_Insurance = sum(Finance_Insurance),
      RealEstate = sum(RealEstate),
      STEM = sum(STEM),
      CorpManagement = sum(CorpManagement),
      WasteManagement = sum(WasteManagement),
      Education = sum(Education),
      Health_SocialAssistance = sum(Health_SocialAssistance),
      Arts = sum(Arts),
      Accommodations_FoodService = sum(Accommodations_FoodService),
      OtherServices = sum(OtherServices),
      PublicAdmin = sum(PublicAdmin)
  )

 CountryProp <- CountryByState %>%
  select(state_name, TotalJobLossIndex, total_li_workers_employed, Agriculture, Mining, Utilities, Construction, Manufacturing, Wholesale_Trade, Retail_Trade, Transportation_Warehousing, Information, Finance_Insurance, RealEstate, STEM, CorpManagement, WasteManagement, Education, Health_SocialAssistance, Arts, Accommodations_FoodService, OtherServices, PublicAdmin) %>%
      summarize (
      AgricultureLossPerWorker = sum(Agriculture) / sum(total_li_workers_employed),
      MiningLossPerWorker = sum(Mining) / sum(total_li_workers_employed),
      UtilitiesLossPerWorker = sum(Utilities) / sum(total_li_workers_employed),
      ConstructionLossPerWorker = sum(Construction) / sum(total_li_workers_employed),
      ManufacturingLossPerWorker = sum(Manufacturing) / sum(total_li_workers_employed),
      Wholesale_TradeLossPerWorker = sum(Wholesale_Trade) / sum(total_li_workers_employed),
      Retail_TradeLossPerWorker = sum(Retail_Trade) / sum(total_li_workers_employed),
      Transportation_WarehousingLossPerWorker = sum(Transportation_Warehousing) / sum(total_li_workers_employed),
      InformationLossPerWorker = sum(Information) / sum(total_li_workers_employed),
      Finance_InsuranceLossPerWorker = sum(Finance_Insurance) / sum(total_li_workers_employed),
      RealEstateLossPerWorker = sum(RealEstate) / sum(total_li_workers_employed),
      STEMLossPerWorker = sum(STEM) / sum(total_li_workers_employed),
      CorpManagementLossPerWorker = sum(CorpManagement) / sum(total_li_workers_employed),
      WasteManagementLossPerWorker = sum(WasteManagement) / sum(total_li_workers_employed),
      EducationLossPerWorker = sum(Education) / sum(total_li_workers_employed),
      Health_SocialAssistanceLossPerWorker = sum(Health_SocialAssistance) / sum(total_li_workers_employed),
      ArtsLossPerWorker = sum(Arts) / sum(total_li_workers_employed),
      Accommodations_FoodServiceLossPerWorker = sum(Accommodations_FoodService) / sum(total_li_workers_employed),
      OtherServicesLossPerWorker = sum(OtherServices) / sum(total_li_workers_employed),
      PublicAdminLossPerWorker = sum(PublicAdmin) / sum(total_li_workers_employed)
  )


Thingy <- as.data.frame(t(CountryProp))
Thing2 <- tibble::rownames_to_column(Thingy, "VALUE")
CountryProp <- setNames(Thing2, c("FieldName","ProportionOfJobsLostInEachField"))

CountryByCount <- CountryByState %>%
  select(state_name, TotalJobLossIndex, total_li_workers_employed, Agriculture, Mining, Utilities, Construction, Manufacturing, Wholesale_Trade, Retail_Trade, Transportation_Warehousing, Information, Finance_Insurance, RealEstate, STEM, CorpManagement, WasteManagement, Education, Health_SocialAssistance, Arts, Accommodations_FoodService, OtherServices, PublicAdmin) %>%
      summarize (
      AgricultureLossPerWorker = sum(Agriculture),
      MiningLossPerWorker = sum(Mining),
      UtilitiesLossPerWorker = sum(Utilities),
      ConstructionLossPerWorker = sum(Construction),
      ManufacturingLossPerWorker = sum(Manufacturing),
      Wholesale_TradeLossPerWorker = sum(Wholesale_Trade),
      Retail_TradeLossPerWorker = sum(Retail_Trade),
      Transportation_WarehousingLossPerWorker = sum(Transportation_Warehousing),
      InformationLossPerWorker = sum(Information),
      Finance_InsuranceLossPerWorker = sum(Finance_Insurance),
      RealEstateLossPerWorker = sum(RealEstate),
      STEMLossPerWorker = sum(STEM),
      CorpManagementLossPerWorker = sum(CorpManagement),
      WasteManagementLossPerWorker = sum(WasteManagement),
      EducationLossPerWorker = sum(Education),
      Health_SocialAssistanceLossPerWorker = sum(Health_SocialAssistance),
      ArtsLossPerWorker = sum(Arts),
      Accommodations_FoodServiceLossPerWorker = sum(Accommodations_FoodService),
      OtherServicesLossPerWorker = sum(OtherServices),
      PublicAdminLossPerWorker = sum(PublicAdmin)
  )

Thingy <- as.data.frame(t(CountryByCount))
Thing2 <- tibble::rownames_to_column(Thingy, "VALUE")
CountryByCount <- setNames(Thing2, c("FieldName","ProportionOfJobsLostInEachField"))
```

## Graphs of All States

```{r}
#Job Loss by State
ggplot(CountryByState, mapping = aes(state_name, ProportionOfJobLossIndexToLowIncomeJobs)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#Job Loss by Total Count (Go look at STEM and Transportation if you want)
ggplot(CountryByCount, mapping = aes(FieldName, ProportionOfJobsLostInEachField)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#Job Loss by Proportion (I feel the one above is more useful)
ggplot(CountryProp, mapping = aes(FieldName, ProportionOfJobsLostInEachField)) +
  geom_bar(stat = "identity", fill = "lightblue", color = "grey") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("Proportion of jobs lost by industry")+
  labs(y = "Proportion",
       x = "Industry Name",
       subtitle = " Proportion = industry LIJs lost/ net LIJs") +
  scale_x_discrete(labels = c("Accommodations & Food Services", "Agriculture", "Arts", "Construction", "Corp. Management", "Education", "Finance & Insurance", "Health & Social Assistance", "Information", "Manufacturing", "Mining", "Others", "Public Admin", "Real Estate", "Retail and Trade", "STEM", "Transportation & Warehousing", "Utilities", "Waste Management", "Wholesale & Trade"))
# Accommodations and Food Services
# Agriculture
# Arts 
# Construction 
# Corp. Management
# Education 
# Finance and Insurance 
# Health and Social Assistance 
# Information 
# Manufacturing 
# Mining
# Others
# Public Admin
# Real Estate 
# Retail and Trade 
# STEM
# Transportation and Warehousing 
# Utilities
# Waste Management 
# Wholesale and Trade
```