---
title: "DAT4500"
output: html_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(openintro)
library(readxl)
library(plotly)
library(readr)
library(albersusa)

my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())}

us_states <- usa_sf("laea")

Labels <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/lehd_types_s3.csv")
County <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_county.csv")
Tract <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/job_loss_by_tract.csv")
CBSA <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_cbsa.csv")
#Make sure to download for yourself and add in on your own
#Census_Data <- read_excel("C:/Users/zacha/OneDrive/Desktop/Census_Data.xlsx", col_names = FALSE, skip = 10, n_max = 51)

Census_Data <- read.csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/sum_job_loss_cbsa_renamed.csv")

```

## Data

```{r Camalcase}
Lab <- c("TotalJobLossIndex", "Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin")

LabChange <- County[,-1:-3]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- County[,-4:-28]
NoChangeLast <- County[, -1:-24]
County <- cbind(NoChangeFirst, LabChange, NoChangeLast)

LabChange <- CBSA[,-1:-2]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- CBSA[,-3:-27]
NoChangeLast <- CBSA[, -1:-23]
CBSA <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin", "TotalJobLossIndex")

LabChange <- Tract[,-1:-7]
LabChange <- LabChange[,-22:-23]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- Tract[,-8:-30]
NoChangeLast <- Tract[, -1:-28]
Tract1 <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("GeographicArea", "Population_Estimates_Base", "PopEstimate2020", "PopEstimate2021", "PopEstimate2022", "Ranking_Base", "Ranking2020", "Ranking2021", "Ranking2022", "Change_21_22_Number", "Change_21_22_Percent", "Change_20_22_Number", "Change_20_22_Percent", "Ranking_21_22_Number", "Ranking_21_22_Percentage", "Ranking_20_22_Number", "Ranking_20_22_Percentage")

Census_Data <- setNames(Census_Data, Lab)

Census_Data$GeographicArea <- str_replace(Census_Data$GeographicArea, ".", "" )
```

## Graph?

```{r See what comes of this}
TGraph <- Tract %>%
  select(state_name, TotalJobLossIndex)%>%
  group_by(state_name) %>%
    summarize(TJLI = sum(TotalJobLossIndex))
  
TGraph$state_name <- state.abb[match(TGraph$state_name, state.name)]
TGraph$state_name <- replace_na(TGraph$state_name, "DC")

us_states_Tract <- left_join(us_states, TGraph, c("iso_3166_2"="state_name"))

Census_Data$GeographicArea <- state.abb[match(Census_Data$GeographicArea, state.name)]
Census_Data$GeographicArea <- replace_na(Census_Data$GeographicArea, "DC")

USStatesTract <- left_join(us_states_Tract, Census_Data, c("iso_3166_2" = "GeographicArea"))

USStatesTract$Proportion <- USStatesTract$TJLI / USStatesTract$PopEstimate2020


ggplot(USStatesTract) +
  geom_sf(aes(fill = Proportion)) +
  scale_fill_continuous(low="yellow", high="red") +
  my_map_theme()
```


```{r}
Labels <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/lehd_types_s3.csv")
County <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_county.csv")
Tract <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/job_loss_by_tract.csv")
CBSA <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_cbsa.csv")
```

## Data

```{r Camalcase}
Lab <- c("TotalJobLossIndex", "Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin")

LabChange <- County[,-1:-3]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- County[,-4:-28]
NoChangeLast <- County[, -1:-24]
County <- cbind(NoChangeFirst, LabChange, NoChangeLast)

LabChange <- CBSA[,-1:-2]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- CBSA[,-3:-27]
NoChangeLast <- CBSA[, -1:-23]
CBSA <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin", "TotalJobLossIndex")

LabChange <- Tract[,-1:-7]
LabChange <- LabChange[,-22:-23]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- Tract[,-8:-30]
NoChangeLast <- Tract[, -1:-28]
Tract <- cbind(NoChangeFirst, LabChange, NoChangeLast)
```

## Recompile for All States

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(openintro)
library(readxl)
library(plotly)
library(readr)
library(tibble)
library(albersusa)

my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())}

us_states <- usa_sf()
us_county <- counties_sf("laea")

Labels <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/lehd_types_s3.csv")
County <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_county.csv")
Tract <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/job_loss_by_tract.csv")
CBSA <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_cbsa.csv")

Lab <- c("TotalJobLossIndex", "Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin")

LabChange <- County[,-1:-3]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- County[,-4:-28]
NoChangeLast <- County[, -1:-24]
County <- cbind(NoChangeFirst, LabChange, NoChangeLast)

LabChange <- CBSA[,-1:-2]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- CBSA[,-3:-27]
NoChangeLast <- CBSA[, -1:-23]
CBSA <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin", "TotalJobLossIndex")

LabChange <- Tract[,-1:-7]
LabChange <- LabChange[,-22:-23]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- Tract[,-8:-30]
NoChangeLast <- Tract[, -1:-28]
Tract <- cbind(NoChangeFirst, LabChange, NoChangeLast)

CountryByState <- County %>%
  select(state_name, TotalJobLossIndex, total_li_workers_employed, Agriculture, Mining, Utilities, Construction, Manufacturing, Wholesale_Trade, Retail_Trade, Transportation_Warehousing, Information, Finance_Insurance, RealEstate, STEM, CorpManagement, WasteManagement, Education, Health_SocialAssistance, Arts, Accommodations_FoodService, OtherServices, PublicAdmin)%>%
  group_by(state_name) %>%
    summarize(
      ProportionOfJobLossIndexToLowIncomeJobs = sum(TotalJobLossIndex) / sum(total_li_workers_employed),
      TotalJobLossIndex = sum(TotalJobLossIndex),
      total_li_workers_employed = sum(total_li_workers_employed),
      Agriculture = sum(Agriculture),
      Mining = sum(Mining),
      Utilities = sum(Utilities),
      Construction = sum(Construction),
      Manufacturing = sum(Manufacturing),
      Wholesale_Trade = sum(Wholesale_Trade),
      Retail_Trade = sum(Retail_Trade),
      Transportation_Warehousing = sum(Transportation_Warehousing),
      Information = sum(Information),
      Finance_Insurance = sum(Finance_Insurance),
      RealEstate = sum(RealEstate),
      STEM = sum(STEM),
      CorpManagement = sum(CorpManagement),
      WasteManagement = sum(WasteManagement),
      Education = sum(Education),
      Health_SocialAssistance = sum(Health_SocialAssistance),
      Arts = sum(Arts),
      Accommodations_FoodService = sum(Accommodations_FoodService),
      OtherServices = sum(OtherServices),
      PublicAdmin = sum(PublicAdmin)
  )

us_states <- usa_sf("laea")

my_cutpoints <- c(-0.1 ,0 ,0.05 , 0.1 , 0.15, 0.2)
my_labels <- c("<0", "0 - 0.05", "0.05 - 0.1", "0.1 - 0.15" , "0.15<")

#join us_states data with covid-19 vaccination data
mapdata1 <- left_join(us_states, CountryByState, by = c("name" = "state_name")) %>% 
  mutate(mar = cut(ProportionOfJobLossIndexToLowIncomeJobs, breaks = my_cutpoints, labels = my_labels))

#add colors
my_colors <- c("#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84",
                        "white","#c7e9b4")
#initial map
ggplot(mapdata1) +
  geom_sf(aes(fill= mar), color = "black") +
  my_map_theme() +
  scale_fill_manual("Proportion", values = my_colors) +
  labs(title="Proportion of Low Income Jobs Lost Due To COVID-19") +
  theme(legend.position = "top", legend.direction = "horizontal")

```