---
title: "Graphs"
author: "Janelle Acob"
date: "05.15.23"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(albersusa)
library(plotly)
library(ggplot2)
covid19_vaccinations_state_prop <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/rate_of_vaccination/covid19_vaccinations_state_prop.csv", skip = 4)
my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())
}
```

### Vaccination Rates 

Proportion relative tot state population

```{r}
# first, filter data
covid19_vaccinations_state_prop_new <- covid19_vaccinations_state_prop %>%
  rename("State_Territory" = `Jurisdiction (State/Territory) or Federal Entity`, 
         "Total_doses_distrubuted" = `Total doses distributed`,
         "Doses_distributed_per_100K_pop" = `Doses distributed per 100K pop`,
         "Doses_admin_by_jurisdiction_per_100K_pop" = `Doses administered by jurisdiction per 100K pop`,
         "Percent_total_pop_with_completed_primary_series" = `Percent of total pop with a completed primary series`,
         "Percent_total_pop_with_at_least_one_dose" = `Percent of total pop with at least one dose`) %>% 
  mutate(State_Territory = str_replace(State_Territory, "New York State", "New York")) %>% 
  mutate(Doses_admin_by_jurisdiction_per_100K_pop = as.integer(Doses_admin_by_jurisdiction_per_100K_pop)) %>% 
  mutate(Percent_total_pop_with_completed_primary_series = as.integer(Percent_total_pop_with_completed_primary_series)) %>% 
  mutate(Percent_total_pop_with_at_least_one_dose = as.integer(Percent_total_pop_with_at_least_one_dose))

# join with geographic data for map
us_states <- usa_sf("laea")

#Cut points need to be the edges of your data, so the labels match the amount of space
#create cutpoints & labels
my_cutpoints <- c(0, 100000, 150000, 200000, 250000, 400000)
my_labels <- c("0 - 100,000 +", "100,001 - 150,000", "150,001 - 200,000", "200,001 - 250,000", "250,000 +")

#join us_states data with covid-19 vaccination data
mapdata1 <- left_join(us_states, covid19_vaccinations_state_prop_new, by = c("name" = "State_Territory")) %>% 
  mutate(mar = cut(Doses_admin_by_jurisdiction_per_100K_pop, breaks = my_cutpoints, labels = my_labels))

#add colors
my_colors <- c("#0c2c84","#225ea8","#1d91c0","#41b6c4", 
                        "#7fcdbb","#c7e9b4", "white") 

#mar != margins
#initial map
ggplot(mapdata1) +
  geom_sf(aes(fill= mar), color = "black") +
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  labs(title="Total Doses Administered Reported\n to the CDC by State/Territory and\n for Select Federal Entities per\n 100K of the Total Population") +
  theme(legend.position = "top", legend.direction = "horizontal")
```
### Extra Stuff (cont.)

```{r}
#Changed around the cutpoints to try to encapsulate the data better, feel free to use whichever you want.
#create cutpoints & labels
my_cutpoints <- c(100000, 150000, 175000, 200000, 250000, 400000)
my_labels <- c("100,000 - 150,000", "150,001 - 175,000", "175,001 - 200,000", "200,001 - 250,000", "250,000 +")

#join us_states data with covid-19 vaccination data
mapdata1 <- left_join(us_states, covid19_vaccinations_state_prop_new, by = c("name" = "State_Territory")) %>% 
  mutate(mar = cut(Doses_admin_by_jurisdiction_per_100K_pop, breaks = my_cutpoints, labels = my_labels))

#add colors
my_colors <- c("#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84",
                        "white","#c7e9b4")
#initial map
ggplot(mapdata1) +
  geom_sf(aes(fill= mar), color = "black") +
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  labs(title="Total Doses Administered Reported to the CDC by State/Territory\n and for Select Federal Entities per 100K of the Total Population") +
  theme(legend.position = "top", legend.direction = "horizontal")
```


### Length of Vaccine Availability (completed series)

This is for Completed Series

```{r}
# first, filter data
covid19_vaccinations_state_prop_new <- covid19_vaccinations_state_prop %>%
  rename("State_Territory" = `Jurisdiction (State/Territory) or Federal Entity`, 
         "Total_doses_distrubuted" = `Total doses distributed`,
         "Doses_distributed_per_100K_pop" = `Doses distributed per 100K pop`,
         "Doses_admin_by_jurisdiction_per_100K_pop" = `Doses administered by jurisdiction per 100K pop`,
         "Percent_total_pop_with_completed_primary_series" = `Percent of total pop with a completed primary series`) %>%
  mutate(State_Territory = str_replace(State_Territory, "New York State", "New York")) %>% 
  mutate(Doses_admin_by_jurisdiction_per_100K_pop = as.integer(Doses_admin_by_jurisdiction_per_100K_pop)) %>% 
  mutate(Percent_total_pop_with_completed_primary_series = as.integer(Percent_total_pop_with_completed_primary_series))

# join with geographic data for map
us_states <- usa_sf("laea")

#Changed around the cutpoints to try to encapsulate the data better, feel free to use whichever you want.
#create cutpoints & labels
my_cutpoints <- c(40, 50, 65, 70, 90, 100)
my_labels <- c("40 - 50%", "50 - 65%", "65 - 70%", "70 - 90%", "90% +")

#join us_states data with covid-19 vaccination data
mapdata1 <- left_join(us_states, covid19_vaccinations_state_prop_new, by = c("name" = "State_Territory")) %>% 
  mutate(mar = cut(Percent_total_pop_with_completed_primary_series, breaks = my_cutpoints, labels = my_labels))

#add colors
my_colors <- c("#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84",
                        "white","#c7e9b4")
#initial map
ggplot(mapdata1) +
  geom_sf(aes(fill= mar), color = "black") +
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  labs(title="Percent Total Population with Completed Series reported to\nthe CDC by State/Territory and for Select Federal Entities") +
  theme(legend.position = "top", legend.direction = "horizontal")
```

### Length of Vaccine Availability (With at least one dose)

```{r}
# first, filter data
covid19_vaccinations_state_prop_new <- covid19_vaccinations_state_prop %>%
  rename("State_Territory" = `Jurisdiction (State/Territory) or Federal Entity`, 
         "Percent_total_pop_with_completed_primary_series" = `Percent of total pop with a completed primary series`,
         "Percent_total_pop_with_at_least_one_dose" = `Percent of total pop with at least one dose`) %>% 
  mutate(State_Territory = str_replace(State_Territory, "New York State", "New York")) %>%
  mutate(Percent_total_pop_with_completed_primary_series = as.integer(Percent_total_pop_with_completed_primary_series)) %>% 
  mutate(Percent_total_pop_with_at_least_one_dose = as.integer(Percent_total_pop_with_at_least_one_dose))

# join with geographic data for map
us_states <- usa_sf("laea")

#Changed around the cutpoints to try to encapsulate the data better, feel free to use whichever you want.
#create cutpoints & labels
my_cutpoints <- c(50, 60, 70, 80, 90, 100)
my_labels <- c("50 - 60%", "60 - 70%", "70 - 80%", "80 - 90%", "90% +")

#join us_states data with covid-19 vaccination data
mapdata1 <- left_join(us_states, covid19_vaccinations_state_prop_new, by = c("name" = "State_Territory")) %>% 
  mutate(mar = cut(Percent_total_pop_with_at_least_one_dose, breaks = my_cutpoints, labels = my_labels))

#add colors
my_colors <- c("#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84",
                        "white","#c7e9b4")
#initial map
ggplot(mapdata1) +
  geom_sf(aes(fill= mar), color = "black") +
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  labs(title="Percent Total Population with at least one dose reported to\nthe CDC by State/Territory and for Select Federal Entities") +
  theme(legend.position = "top", legend.direction = "horizontal")

View(mapdata1)
```

```{r}
politcal <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/political_votes_2020/Popular%20vote%20backend%20-%20Sheet1.csv")
library(dplyr)

politcal$prop_dem <- as.numeric(gsub("%", "", politcal$dem_percent))/100

politcal$prop_rep <- as.numeric(gsub("%", "", politcal$rep_percent))/100

politcal$party <- politcal$called

mapdata1$party <- politcal$party

library(ggplot2)
remotes::install_github("coolbutuseless/ggpattern")

my_colors <- c("#A22015","#DC4631","#6783B8","#0E2549","navy")


library(ggplot2)
library(ggpattern)
library(maps)
devtools::install_github("wmurphyrd/fiftystater")
library(fiftystater)

states <- rbind(map_data("state"))

states <- fifty_states
#states <- map_data("state")

info <- covid19_vaccinations_state_prop_new


info$State_Territory <- tolower(info$State_Territory)
info$region <- info$state_territory
choro <- merge(states, info, sort = FALSE, by.x = "id", by.y = "State_Territory",all.x = TRUE)

choro <- choro[order(choro$order), ]

choro$mar <- cut(choro$Percent_total_pop_with_at_least_one_dose, breaks = my_cutpoints, labels = my_labels)


ggplot(choro, aes(long, lat)) +
  geom_polygon_pattern(aes(group = group, fill = mar), color = "black", pattern = "stripe") +
  coord_map("albers",  lat0 = 45.5, lat1 = 29.5)+
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  labs(title="Percent Total Population with at least one dose reported to\nthe CDC by State/Territory and for Select Federal Entities") +
  theme(legend.position = "top", legend.direction = "horizontal")

politcal$region <- tolower(politcal$state)



choro$party <- vector("character", nrow(choro))

for (i in 1:nrow(choro)) {
  region <- choro[i, "id"]
  p <- politcal$party[politcal$region == region]
  choro[i, "party"] <- p
}



ggplot(choro, aes(long, lat, pattern = party)) +
  geom_polygon_pattern(aes(group = group, fill = mar), color = "black", pattern_fill = "white") +
  coord_map("albers",  lat0 = 45.5, lat1 = 29.5)+
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  labs(title="Percent Total Population with at least one dose reported to\nthe CDC by State/Territory and for Select Federal Entities",
       pattern = "Political Party") +
  theme(legend.position = "top", legend.direction = "horizontal")+ 
  scale_pattern_type_manual(values = c(R="stripe",D="none"), 
                            guide = guide_legend(title = "Political Party"))+ 
  guides(
    pattern = guide_legend(
      override.aes = list(fill = "black"),
      title = "Political Party",
      labels = c("Republican", "Democratic")
    ),
    fill = guide_legend(override.aes = list(pattern = "none"))
  )

ggplot(choro, aes(long, lat, pattern = party)) +
  geom_polygon_pattern(aes(group = group, fill = mar), color = "black", pattern_fill = "white") +
  coord_map("albers", lat0 = 45.5, lat1 = 29.5) +
  my_map_theme() +
  scale_fill_manual("", values = my_colors) +
  scale_pattern_manual(
    values = c(R = "stripe", D = "none"),
    labels = c(R = "Republican", D = "Democratic"),
    guide = guide_legend(title = "Political Party")
  ) +
  labs(
    title = "Percent Total Population with at least one dose reported\nto the CDC by State/Territory and for Select Federal Entities"
  ) +
  theme(legend.position = "top", legend.direction = "horizontal") +
  guides(fill = guide_legend(override.aes = list(pattern = "none")))

my_cutpoints1 <- c(40, 50, 60, 70, 80, 100)
my_labels1 <- c("40 - 50%", "50 - 60%", "60 - 70%", "70 - 80%", "80% +")

choro$mar1 <- cut(choro$Percent_total_pop_with_completed_primary_series, breaks = my_cutpoints1, labels = my_labels1)

#add colors
#my_colors1 <- c("#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84","white","#c7e9b4")

my_colors1 <- my_colors

ggplot(choro, aes(long, lat, pattern = party)) +
  geom_polygon_pattern(aes(group = group, fill = mar1), color = "black", pattern_fill = "white") +
  coord_map("albers", lat0 = 45.5, lat1 = 29.5) +
  my_map_theme() +
  scale_fill_manual("", values = my_colors1) +
  scale_pattern_manual(
    values = c(R = "stripe", D = "none"),
    labels = c(R = "Republican", D = "Democratic"),
    guide = guide_legend(title = "Political Party")
  ) +
  labs(
    title = "Percent Total Population with Completed Series reported to\nthe CDC by State/Territory and for Select Federal Entities"
  ) +
  theme(legend.position = "top", legend.direction = "horizontal") +
  guides(fill = guide_legend(override.aes = list(pattern = "none")))
```
