---
title: "DAT4500"
output: html_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(openintro)
library(readxl)
library(plotly)
library(readr)
library(tibble)
library(albersusa)
library(stringr)

my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())}

us_states <- usa_sf()
us_county <- counties_sf("laea")

Labels <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/lehd_types_s3.csv")
County <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_county.csv")
Tract <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/job_loss_by_tract.csv")
CBSA <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_cbsa.csv")

StateTax <- read_csv("TaxFoundation.csv")
```

## Data

```{r Camalcase}
Lab <- c("TotalJobLossIndex", "Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin")

LabChange <- County[,-1:-3]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- County[,-4:-28]
NoChangeLast <- County[, -1:-24]
County <- cbind(NoChangeFirst, LabChange, NoChangeLast)

LabChange <- CBSA[,-1:-2]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- CBSA[,-3:-27]
NoChangeLast <- CBSA[, -1:-23]
CBSA <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin", "TotalJobLossIndex")

LabChange <- Tract[,-1:-7]
LabChange <- LabChange[,-22:-23]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- Tract[,-8:-30]
NoChangeLast <- Tract[, -1:-28]
Tract <- cbind(NoChangeFirst, LabChange, NoChangeLast)
```

## Tax  

```{r}
CountByState <- County %>%
  select(state_name, TotalJobLossIndex, total_li_workers_employed, Agriculture, Mining, Utilities, Construction, Manufacturing, Wholesale_Trade, Retail_Trade, Transportation_Warehousing, Information, Finance_Insurance, RealEstate, STEM, CorpManagement, WasteManagement, Education, Health_SocialAssistance, Arts, Accommodations_FoodService, OtherServices, PublicAdmin)%>%
  group_by(state_name) %>%
    summarize(
      ProportionOfJobLossIndexToLowIncomeJobs = sum(TotalJobLossIndex) / sum(total_li_workers_employed),
      TotalJobLossIndex = sum(TotalJobLossIndex),
      total_li_workers_employed = sum(total_li_workers_employed),
      Agriculture = sum(Agriculture),
      Mining = sum(Mining),
      Utilities = sum(Utilities),
      Construction = sum(Construction),
      Manufacturing = sum(Manufacturing),
      Wholesale_Trade = sum(Wholesale_Trade),
      Retail_Trade = sum(Retail_Trade),
      Transportation_Warehousing = sum(Transportation_Warehousing),
      Information = sum(Information),
      Finance_Insurance = sum(Finance_Insurance),
      RealEstate = sum(RealEstate),
      STEM = sum(STEM),
      CorpManagement = sum(CorpManagement),
      WasteManagement = sum(WasteManagement),
      Education = sum(Education),
      Health_SocialAssistance = sum(Health_SocialAssistance),
      Arts = sum(Arts),
      Accommodations_FoodService = sum(Accommodations_FoodService),
      OtherServices = sum(OtherServices),
      PublicAdmin = sum(PublicAdmin)
  )

StateTax <- setNames(StateTax, c("State", "Property", "GeneralSales", "IndividualIncome", "CorporateIncome", "OtherTax"))

StateTax$IndividualIncome <-str_replace_all(StateTax$IndividualIncome, "%", "")

StateTax$IndividualIncome <- as.numeric(StateTax$IndividualIncome) /100

StateTaxJobLoss <- left_join(CountByState, StateTax, c("state_name" = "State"))

summary(lm(ProportionOfJobLossIndexToLowIncomeJobs ~ IndividualIncome, data = StateTaxJobLoss))

cor.test(StateTaxJobLoss$IndividualIncome, StateTaxJobLoss$ProportionOfJobLossIndexToLowIncomeJobs)
```















