---
title: "Lab Name"
author: "Author Name"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(corrr)
library(openintro)
library(readxl)
library(plotly)
library(readr)
library(tibble)
library(albersusa)
library(stringr)
library(ggcorrplot)
library(FactoMineR)
library(factoextra)

Labels <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/lehd_types_s3.csv")
County <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_county.csv")
Tract <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/job_loss_by_tract.csv")
CBSA <- read_csv("https://ui-lodes-job-change-public.s3.amazonaws.com/sum_job_loss_cbsa.csv")


```

## PCA Set-up

### Income Tax

```{r}
Lab <- c("TotalJobLossIndex", "Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin")

StateTax <- read_csv("TaxFoundation.csv")

LabChange <- County[,-1:-3]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- County[,-4:-28]
NoChangeLast <- County[, -1:-24]
County <- cbind(NoChangeFirst, LabChange, NoChangeLast)

LabChange <- CBSA[,-1:-2]
LabChange <- LabChange[,-22:-25]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- CBSA[,-3:-27]
NoChangeLast <- CBSA[, -1:-23]
CBSA <- cbind(NoChangeFirst, LabChange, NoChangeLast)

Lab <- c("Agriculture", "Mining", "Utilities", "Construction", "Manufacturing", "Wholesale_Trade", "Retail_Trade", "Transportation_Warehousing", "Information", "Finance_Insurance", "RealEstate", "STEM", "CorpManagement", "WasteManagement", "Education", "Health_SocialAssistance", "Arts", "Accommodations_FoodService", "OtherServices", "PublicAdmin", "TotalJobLossIndex")

LabChange <- Tract[,-1:-7]
LabChange <- LabChange[,-22:-23]
LabChange <- setNames(LabChange, Lab)
NoChangeFirst <- Tract[,-8:-30]
NoChangeLast <- Tract[, -1:-28]
Tract <- cbind(NoChangeFirst, LabChange, NoChangeLast)

CountByState <- County %>%
  select(state_name, TotalJobLossIndex, total_li_workers_employed, Agriculture, Mining, Utilities, Construction, Manufacturing, Wholesale_Trade, Retail_Trade, Transportation_Warehousing, Information, Finance_Insurance, RealEstate, STEM, CorpManagement, WasteManagement, Education, Health_SocialAssistance, Arts, Accommodations_FoodService, OtherServices, PublicAdmin)%>%
  group_by(state_name) %>%
    summarize(
      ProportionOfJobLossIndexToLowIncomeJobs = sum(TotalJobLossIndex) / sum(total_li_workers_employed),
      TotalJobLossIndex = sum(TotalJobLossIndex),
      total_li_workers_employed = sum(total_li_workers_employed),
      Agriculture = sum(Agriculture),
      Mining = sum(Mining),
      Utilities = sum(Utilities),
      Construction = sum(Construction),
      Manufacturing = sum(Manufacturing),
      Wholesale_Trade = sum(Wholesale_Trade),
      Retail_Trade = sum(Retail_Trade),
      Transportation_Warehousing = sum(Transportation_Warehousing),
      Information = sum(Information),
      Finance_Insurance = sum(Finance_Insurance),
      RealEstate = sum(RealEstate),
      STEM = sum(STEM),
      CorpManagement = sum(CorpManagement),
      WasteManagement = sum(WasteManagement),
      Education = sum(Education),
      Health_SocialAssistance = sum(Health_SocialAssistance),
      Arts = sum(Arts),
      Accommodations_FoodService = sum(Accommodations_FoodService),
      OtherServices = sum(OtherServices),
      PublicAdmin = sum(PublicAdmin)
  )

StateTax <- setNames(StateTax, c("State", "Property", "GeneralSales", "IndividualIncome", "CorporateIncome", "OtherTax"))

CountByState$LowIncomeJobsLostProportion <- (CountByState$Agriculture + CountByState$Mining + CountByState$Utilities + CountByState$Construction + CountByState$Manufacturing + CountByState$Wholesale_Trade + CountByState$Retail_Trade + CountByState$Transportation_Warehousing + CountByState$Information + CountByState$Finance_Insurance + CountByState$RealEstate + CountByState$STEM + CountByState$CorpManagement + CountByState$WasteManagement + CountByState$Education + CountByState$Health_SocialAssistance + CountByState$Arts + CountByState$Accommodations_FoodService + CountByState$OtherServices + CountByState$PublicAdmin) / CountByState$total_li_workers_employed

StateTax$IndividualIncome <-str_replace_all(StateTax$IndividualIncome, "%", "")

StateTax$IndividualIncome <- as.numeric(StateTax$IndividualIncome) /100

PCA1 <- left_join(CountByState, StateTax, c("state_name" = "State")) %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome)
  

```

### Health Index

```{r}
QoL <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/QoL/QoL.csv")
JL <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/Mask_Req_Length/JL_by_state.csv")

PCA2 <- merge(PCA1, QoL, by.x = "state_name", by.y = "state") %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome, healthCareRank_21)
```

### Length of Vacination availibility

```{r}
remote_work_2021 <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/Remote_Work/remote_work_2021.csv")
covid19_vaccinations_state_prop <- read_csv("covid19_vaccinations_state_prop.csv", skip = 4)

covid19_vaccinations_state_prop_new <- covid19_vaccinations_state_prop %>%
  rename("State_Territory" = `Jurisdiction (State/Territory) or Federal Entity`, 
         "Total_doses_distrubuted" = `Total doses distributed`,
         "Doses_distributed_per_100K_pop" = `Doses distributed per 100K pop`,
         "DosesAdministered" = `Doses administered by jurisdiction per 100K pop`,
         "Percent_total_pop_with_completed_primary_series" = `Percent of total pop with a completed primary series`,
         "Percent_total_pop_with_at_least_one_dose" = `Percent of total pop with at least one dose`) %>% 
  mutate(State_Territory = str_replace(State_Territory, "New York State", "New York")) %>% 
  mutate(DosesAdministered = as.integer(DosesAdministered)) %>% 
  mutate(Percent_total_pop_with_completed_primary_series = as.integer(Percent_total_pop_with_completed_primary_series)) %>% 
  mutate(Percent_total_pop_with_at_least_one_dose = as.integer(Percent_total_pop_with_at_least_one_dose))

PCA3 <- left_join(PCA2, covid19_vaccinations_state_prop_new, by = c("state_name" = "State_Territory")) %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome, healthCareRank_21, DosesAdministered)
```

### Remote Jobs

```{r}
remote_work_2021 <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/Remote_Work/remote_work_2021.csv")

remote_work_2021$ProportionOfRemoteWorkers <- remote_work_2021$Proportion_Remote_Workers

PCA4 <- left_join(PCA3, remote_work_2021, by = c("state_name" = "State")) %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome, healthCareRank_21, DosesAdministered, ProportionOfRemoteWorkers)
```

### Masks


```{r}
data <- read_csv("masks.csv")

mycols <- strsplit(as.character(data$Effective), "; ")
mycols <- do.call(rbind, mycols)
colnames(mycols) <- c("Effective_Initial", "Effective_Updated")
data <- cbind(data, mycols)
data$Effective <- NULL

for (i in 1:nrow(data)) {
  if (data$Effective_Initial[i] == data$Effective_Updated[i]) {
    data$Effective_Updated[i] <- NA
  }
}


mycols <- strsplit(as.character(data$`Type of order ending the mandate`), "; ")
mycols <- do.call(rbind, mycols)
colnames(mycols) <- c("EOT_Initial", "EOT_Updated")
data <- cbind(data, mycols)
data$`Type of order ending the mandate` <- NULL

write.csv(data, file = "masks_1.csv")
data <- read_csv("masks_1.csv")

mycols <- strsplit(as.character(data$`Number of days effective`), ";")
mycols <- do.call(rbind, mycols)
colnames(mycols) <- c("Days_Initial", "Days_Updated")
data <- cbind(data, mycols)
data$`Number of days effective` <- NULL

for (i in 1:nrow(data)) {
  if (data$Days_Initial[i] == data$Days_Updated[i]) {
    data$Days_Updated[i] <- NA
  }
}

data$Effective_Initial <- as.Date(data$Effective_Initial, format = "%B %d, %Y")
data$Effective_Updated <- as.Date(data$Effective_Updated, format = "%B %d, %Y")

data$VaccExempt <- as.Date(data$Effective_Initial) + as.numeric(data$Days_Initial)
data$VaccExempt <- as.Date(data$VaccExempt)

data$VaccExempt_Updated <- as.Date(data$Effective_Updated) + as.numeric(data$Days_Updated)
data$VaccExempt_Updated <- as.Date(data$VaccExempt_Updated)

data$Days_Initial <- replace(data$Days_Initial, is.na(data$Days_Initial), 0)

data$Days_Updated <- replace(data$Days_Updated, is.na(data$Days_Updated), 0)

data$TotalTime <- as.numeric(data$Days_Initial) + as.numeric(data$Days_Updated)

data$TotalDaysOfMaskMandate <- replace(data$TotalTime, is.na(data$TotalTime), 0)

PCA5 <- left_join(PCA4, data, by = c("state_name" = "State")) %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome, healthCareRank_21, DosesAdministered, ProportionOfRemoteWorkers, TotalDaysOfMaskMandate)
```

### Personal Income

```{r}
PI <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/personal_income/income.csv")

PI$dif <- PI$`2018` - PI$`2021`
PI$AnnualIncomeDifference <- PI$`2021` - PI$`2018`

PCA6 <- left_join(PCA5, PI, by = c("state_name" = "GeoName")) %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome, healthCareRank_21, DosesAdministered, ProportionOfRemoteWorkers, TotalDaysOfMaskMandate, AnnualIncomeDifference)
```



```{r}
political <- read_csv("https://raw.githubusercontent.com/Yarrabozaed/Data-and-Society/main/Hypothesis_Testing/political_votes_2020/Popular%20vote%20backend%20-%20Sheet1.csv")

political$ProportionDemocratic <- as.numeric(gsub("%", "", political$dem_percent))/100

political$ProportionRepublican <- as.numeric(gsub("%", "", political$rep_percent))/100

PCA7 <- left_join(PCA6, political, by = c("state_name" = "state")) %>%
  select(state_name, LowIncomeJobsLostProportion, IndividualIncome, healthCareRank_21, DosesAdministered, ProportionOfRemoteWorkers, TotalDaysOfMaskMandate, AnnualIncomeDifference, ProportionDemocratic)
```

### Gathering Size

```{r}
Bans <- read_csv("https://data.cdc.gov/api/views/3qs9-qnbs/rows.csv?accessType=DOWNLOAD")
```

##Data

```{r}
Bans$Date <- as.Date(Bans$Date)

Bans_filtered <- Bans %>% filter(General_or_Under_6ft_Bans_Gatherings_Over != -1)

max_ban_duration_by_state <- Bans_filtered %>%
  group_by(State_Tribe_Territory) %>%
  summarize(BanDuration = max(Date) - min(Date))

az <- data.frame(State_Tribe_Territory = "Arizona", BanDuration = 0)
nd <- data.frame(State_Tribe_Territory = "North Dakota", BanDuration = 0)
sd <- data.frame(State_Tribe_Territory = "South Dakota", BanDuration = 0)
# add the new row to the existing data frame
max_ban_duration_by_state <- rbind(max_ban_duration_by_state, az)
max_ban_duration_by_state <- rbind(max_ban_duration_by_state, nd)
max_ban_duration_by_state <- rbind(max_ban_duration_by_state, sd)

 max_ban_duration_by_state$GatheringBanDuration <- as.numeric(gsub(" days","", max_ban_duration_by_state$BanDuration))

PCA8 <- left_join(PCA7, max_ban_duration_by_state, by = c("state_name" = "State_Tribe_Territory")) %>%
  select(state_name, LowIncomeJobsLostProportion, healthCareRank_21, DosesAdministered, ProportionOfRemoteWorkers, TotalDaysOfMaskMandate, AnnualIncomeDifference, ProportionDemocratic, GatheringBanDuration)
```

## PCA Stuffs

### Ensure No NAs

```{r}
PrincipalComponentAnalysis <- PCA8

PrincipalComponentAnalysis$TotalDaysOfMaskMandate <- replace(PrincipalComponentAnalysis$TotalDaysOfMaskMandate, is.na(PrincipalComponentAnalysis$TotalDaysOfMaskMandate), 0)

colSums(is.na(PrincipalComponentAnalysis))
```

### Normalize the Data

```{r}
PrincipalComponentAnalysis_1 <- PrincipalComponentAnalysis[,3:9]

PrincipalComponentAnalysis_Standardized <- scale(PrincipalComponentAnalysis_1)
```

### Corrolation Matrix

```{r}
corr_matrix <- cor(PrincipalComponentAnalysis_Standardized)
ggcorrplot(corr_matrix,colors = c("#ef8a62", "#ffffbf", "#67a9cf"))
```

## Applying PCA

```{r}
PrincipalComponentAnalysis_PCA <- princomp(corr_matrix)
summary(PrincipalComponentAnalysis_PCA)

PrincipalComponentAnalysis_PCA$loadings[, 1:2]

fviz_eig(PrincipalComponentAnalysis_PCA, addlabels = TRUE)

fviz_cos2(PrincipalComponentAnalysis_PCA, choice = "var", axes = 1:2)

fviz_pca_var(PrincipalComponentAnalysis_PCA, col.var = "cos2",
            gradient.cols = c("#ef8a62", "black", "#67a9cf"),
            repel = TRUE)
```

```{r}
myPCs <- as.matrix(PrincipalComponentAnalysis_Standardized) %*% PrincipalComponentAnalysis_PCA$loadings[,1]

pc <- prcomp(PrincipalComponentAnalysis_1, center = TRUE, scale. = TRUE)

myPCs2 <- as.data.frame(pc$x[,1:2])

myPCs2$state_name <- PrincipalComponentAnalysis$state_name

myPCs2$LowIncomeJobsLostProportion <- PrincipalComponentAnalysis$LowIncomeJobsLostProportion
```

### Linear Model

```{r}
myPCs2$Component1 <- myPCs2$`pc$x[, 1]`


model1 <- lm(LowIncomeJobsLostProportion ~ PC1 + PC2, data = myPCs2)

summary(model1)
```